apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  type: ClusterIP
  selector:
    app: api-gateway-app
  ports:
    - port: 5000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
spec:
  selector:
    matchLabels:
      app: api-gateway-app
  template:
    metadata:
      labels:
        app: api-gateway-app
    spec:
      containers:
        - name: api-gateway-container
          image: registry.gitlab.com/inf326-2022-2/api-gateway:1.0.1

          ports:
            - containerPort: 5000

      restartPolicy: Always
      imagePullSecrets:
        - name: gitlab-registry

---