services:
  demo_04_service_01:
    build: .
    ports:
      - "5001:80"
    volumes:
      - .:/code
  demo_04_service_events_receiver_01:
    build: .
    volumes:
      - .:/code
    command: python3 app/events.py
  demo_04_service_01_mongodb:
    image: mongo:7
    volumes:
      - demo_04_service_01_mongodb_container:/data/db
    logging:
        driver: none

volumes:
  demo_04_service_01_mongodb_container:

networks:
  default:
    name: microsvcs
    external: true